name: betterftp
description: "betterftp.cc"
publish_to: 'none'

version: 1.1.0+0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.2.1
  go_router: ^17.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fl_chart: ^1.1.1
  wakelock_plus: ^1.1.0
  flutter_blue_plus: ^2.1.1
  fit_sdk: ^0.3.0
  share_plus: ^12.0.1
  path_provider: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  patrol: ^4.5.0
  device_preview: ^1.2.0
  device_preview_screenshot: ^1.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/icon/

  fonts:
    - family: Iosevka
      fonts:
        - asset: assets/fonts/Iosevka-Regular.ttf
          weight: 400
        - asset: assets/fonts/Iosevka-Medium.ttf
          weight: 500
        - asset: assets/fonts/Iosevka-Bold.ttf
          weight: 700
        - asset: assets/fonts/Iosevka-Heavy.ttf
          weight: 900

flutter_launcher_icons:
  android: "ic_launcher"
  ios: false
  image_path: "assets/icon/app_icon_foreground.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/app_icon_foreground.png"
  adaptive_icon_foreground_inset: 16
  remove_alpha_ios: false

patrol:
  app_name: BETTER.FTP
  android:
    package_name: com.example.ftpRampTest
  ios:
    bundle_id: com.example.ftpRampTest
